sonar.projectKey=23deFevereiro_API_5_SEM_BACK
sonar.organization=23defevereiro-1


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=API_5_SEM_BACK
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.exclusions=**/migrations/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**,**/tests/**
