# Generated by Django 6.0.3 on 2026-03-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fornecedor', models.CharField(max_length=20, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Bloqueado', 'Bloqueado')], max_length=20)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Obsoleto', 'Obsoleto')], max_length=20)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programa', models.CharField(max_length=20, unique=True)),
                ('nome_programa', models.CharField(max_length=255)),
                ('gerente_programa', models.CharField(max_length=255)),
                ('gerente_tecnico', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], max_length=20)),
            ],
            options={
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('data_pedido', models.DateField()),
                ('data_previsao_entrega', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Entregue', 'Entregue'), ('Parcialmente Entregue', 'Parcialmente Entregue'), ('Cancelado', 'Cancelado')], max_length=30)),
                ('fornecedor', models.ForeignKey(db_column='fornecedor_id', on_delete=django.db.models.deletion.PROTECT, to='api.fornecedor')),
            ],
            options={
                'db_table': 'pedido_compra',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_projeto', models.CharField(max_length=20, unique=True)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('custo_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('status', models.CharField(choices=[('Planejamento', 'Planejamento'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido'), ('Suspenso', 'Suspenso')], max_length=20)),
                ('programa', models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.PROTECT, to='api.programa')),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='EstoqueMaterialProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('localizacao', models.CharField(max_length=100)),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.PROTECT, to='api.material')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.PROTECT, to='api.projeto')),
            ],
            options={
                'db_table': 'estoque_material_projeto',
            },
        ),
        migrations.CreateModel(
            name='EmpenhoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_empenhada', models.IntegerField()),
                ('data_empenho', models.DateField()),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.PROTECT, to='api.material')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.PROTECT, to='api.projeto')),
            ],
            options={
                'db_table': 'empenho_material',
            },
        ),
        migrations.CreateModel(
            name='ComprasProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido_compra', models.ForeignKey(db_column='pedido_compra_id', on_delete=django.db.models.deletion.PROTECT, to='api.pedidocompra')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.PROTECT, to='api.projeto')),
            ],
            options={
                'db_table': 'compras_projeto',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitacao', models.CharField(max_length=20, unique=True)),
                ('quantidade', models.IntegerField()),
                ('data_solicitacao', models.DateField()),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.PROTECT, to='api.material')),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.PROTECT, to='api.projeto')),
            ],
            options={
                'db_table': 'solicitacao_compra',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tarefa', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('estimativa_horas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('status', models.CharField(choices=[('Nao iniciada', 'Nao iniciada'), ('Em andamento', 'Em andamento'), ('Concluida', 'Concluida'), ('Bloqueada', 'Bloqueada')], max_length=20)),
                ('projeto', models.ForeignKey(db_column='projeto_id', on_delete=django.db.models.deletion.PROTECT, to='api.projeto')),
            ],
            options={
                'db_table': 'tarefa',
            },
        ),
        migrations.CreateModel(
            name='TempoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarefa', models.ForeignKey(db_column='tarefa_id', on_delete=django.db.models.deletion.PROTECT, to='api.tarefa')),
            ],
            options={
                'db_table': 'tempo_tarefa',
            },
        ),
    ]
