name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:


jobs:
  check-migrations:
    runs-on: ubuntu-latest
    name: Check Migrations
    services:
      database:
        image: postgres:18
        env:
          POSTGRES_DB: lunae
          POSTGRES_USER: fev-23
          POSTGRES_PASSWORD: fev-23
        ports:
          - 5432:5432
    env:
      POSTGRES_HOST: localhost
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check missing migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Check migrate
        run: python manage.py migrate

  test:
    runs-on: ubuntu-latest
    name: Test
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: lunae
          POSTGRES_USER: fev-23
          POSTGRES_PASSWORD: fev-23
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check missing migrations
        run: pytest

  general-check:
    runs-on: ubuntu-latest
    name: General checks
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check missing migrations
        run: python manage.py check